name: bulid 2 package

on:
 workflow_dispatch:
  push:
    tags:
      - v*.**
  schedule:
    - cron: "0 */8 * * *"

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - x86_64

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: sbwml/openwrt-gh-action-sdk@go1.20
        env:
          ARCH: ${{ matrix.arch }}-openwrt-22.03
          FEEDNAME: packages_ci
          PACKAGES: luci-app-ssr-plus luci-app-passwall
          NO_REFRESH_CHECK: true

      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
